---
- name: Install Fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    lock_timeout: 300

- name: Enable and start Fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
