---
- name: Ensure SSH Service Is Enabled and Running
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: yes

- name: Configure SSH Hardening
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      X11Forwarding no
  notify: restart-ssh
