voltswitch-api:
  shutdownCommand: 'ssh root@192.168.0.101 "shutdown -h now"'

  secret:
    enabled: false

  externalSecret:
    enabled: true
    storeName: vault
    remoteKey: voltswitch

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: home-ca
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Voltswitch
      gethomepage.dev/group: Workloads
      gethomepage.dev/icon: mdi-power
    hosts:
      - host: voltswitch.home.arpa
        paths:
          - path: /
    tls:
      - secretName: voltswitch-tls
        hosts:
          - voltswitch.home.arpa
