apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/nayetdet/homelab.git
    targetRevision: main
    path: charts/security/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
