apiVersion: v2
name: gatekeeper
description: Local configuration wrapper for the Gatekeeper chart
type: application
version: 0.1.0
dependencies:
  - name: gatekeeper
    version: "*"
    repository: oci://ghcr.io/nayetdet/charts
