apiVersion: v2
name: mirro-world
description: Local configuration wrapper for the Mirro World chart
type: application
version: 0.1.0
dependencies:
  - name: mirro-world
    version: "*"
    repository: oci://ghcr.io/nayetdet/charts
