argo-cd:
  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argocd.home.arpa
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Argo CD
        gethomepage.dev/icon: argocd.png
      tls: true

    certificate:
      enabled: true
      domain: argocd.home.arpa
      issuer:
        group: cert-manager.io
        kind: ClusterIssuer
        name: home-ca
