{{- if .Values.antimeta.files.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.antimeta.files.secretName | quote }}
type: Opaque
stringData:
  resume_en_US.json: |-
{{ .Files.Get "submodules/resume/data/resume_en_US.json" | nindent 4 }}
  resume_pt_BR.json: |-
{{ .Files.Get "submodules/resume/data/resume_pt_BR.json" | nindent 4 }}
{{- end }}
