{{- if .Values.antimeta.files.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.antimeta.files.secretName | quote }}
type: Opaque
stringData:
  resume_en_US.json: |-
{{ .Files.Get "files/resume_en_US.json" | nindent 4 }}
  resume_pt_BR.json: |-
{{ .Files.Get "files/resume_pt_BR.json" | nindent 4 }}
  additional_info.json: |-
{{ .Files.Get "files/additional_info.json" | nindent 4 }}
  classification_patterns.json: |-
{{ .Files.Get "files/classification_patterns.json" | nindent 4 }}
{{- end }}
