pihole:
  maxUnavailable: 0

  hostNetwork: "false"

  dnsHostPort:
    enabled: true
    port: 53

  podDnsConfig:
    enabled: false

  DNS1: 1.1.1.1
  DNS2: 1.0.0.1

  dnsmasq:
    customDnsEntries:
      - address=/home.arpa/192.168.0.201

  serviceDns:
    type: ClusterIP
    mixedService: true

  serviceDhcp:
    enabled: false

  persistentVolumeClaim:
    enabled: true
    size: 1Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: home-ca
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Pi-hole
      gethomepage.dev/group: Networking
      gethomepage.dev/icon: pi-hole.png
      gethomepage.dev/href: https://pihole.home.arpa/admin
    hosts:
      - pihole.home.arpa
    tls:
      - secretName: pihole-tls
        hosts:
          - pihole.home.arpa
