apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: {{ .Release.Namespace }}
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    hideVersion: true
  services.yaml: |
    []
  bookmarks.yaml: |
    []
