apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: {{ .Release.Namespace }}
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  settings.yaml: |
    title: Home
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    hideVersion: true
    layout:
      Workloads:
        style: row
        columns: 3
  services.yaml: |
    []
  bookmarks.yaml: |
    []
