#SPDX-License-Identifier: MIT-0
---
# handlers file for networking
- name: Apply Netplan
  ansible.builtin.command: netplan apply
  changed_when: true

- name: Reload UFW
  ansible.builtin.command: ufw reload
  changed_when: true

- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted
