#SPDX-License-Identifier: MIT-0
---
# handlers file for networking
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Reload UFW
  ansible.builtin.command: ufw reload
  changed_when: true

- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted
