gatekeeper:
  secret:
    enabled: false

  externalSecret:
    enabled: true
    storeName: vault

  filebrowser:
    enabled: true
    auth:
      enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        integrations:
          certManager:
            enabled: true
            certificateIssuer: home-ca
          traefik:
            enabled: true
            entrypoints:
              - websecure
            forceTLS: true
        hosts:
          - host: gatekeeper.home.arpa
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gatekeeper-tls
            hosts:
              - gatekeeper.home.arpa
