gatekeeper:
  secret:
    enabled: false

  externalSecret:
    enabled: true
    storeName: vault

  filebrowser:
    enabled: true
    auth:
      enabled: false
    ingress:
      main:
        enabled: true
        hosts:
          - host: gatekeeper.home.arpa
            paths:
              - path: /
                pathType: Prefix
