#SPDX-License-Identifier: MIT-0
---
# tasks file for tools
- name: Install Fastfetch
  ansible.builtin.import_tasks: fastfetch.yml

- name: Configure Neovim
  ansible.builtin.import_tasks: neovim.yml

- name: Install Terraform
  ansible.builtin.import_tasks: terraform.yml

- name: Install Tailscale
  ansible.builtin.import_tasks: tailscale.yml

- name: Install utility packages
  ansible.builtin.import_tasks: utils.yml

- name: Configure Zsh
  ansible.builtin.import_tasks: zsh.yml
