---
- name: Install Terraform APT dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - python3-debian
    state: present
    update_cache: true
    lock_timeout: 300

- name: Download HashiCorp APT repository key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-apt-key.asc
    mode: "0644"
  register: hashicorp_key_download
  retries: 5
  delay: 10
  until: hashicorp_key_download is succeeded

- name: Install HashiCorp APT repository key
  ansible.builtin.command:
    cmd: gpg --dearmor --yes --output /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp-apt-key.asc
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Configure HashiCorp APT repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - main
    signed_by: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
    lock_timeout: 300
