---
- name: Install Zsh Dependencies
  ansible.builtin.apt:
    name:
      - git
      - zsh
    state: present
    update_cache: true

- name: Resolve User Home Directory
  ansible.builtin.getent:
    database: passwd
    key: "{{ user }}"

- name: Set Zsh Configuration Paths
  ansible.builtin.set_fact:
    zsh_home: "{{ ansible_facts['getent_passwd'][user][4] }}"
    zsh_oh_my_zsh_dir: "{{ ansible_facts['getent_passwd'][user][4] }}/.oh-my-zsh"

- name: Check for Existing Zsh Configuration
  ansible.builtin.stat:
    path: "{{ zsh_home }}/.zshrc"
  register: zshrc

- name: Clone Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_oh_my_zsh_dir }}"
    version: master
    depth: 1
  become_user: "{{ user }}"

- name: Install Zsh Completions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ zsh_oh_my_zsh_dir }}/custom/plugins/zsh-completions"
    version: master
    depth: 1
  become_user: "{{ user }}"

- name: Install Zsh Autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_oh_my_zsh_dir }}/custom/plugins/zsh-autosuggestions"
    version: master
    depth: 1
  become_user: "{{ user }}"

- name: Install Zsh Syntax Highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_oh_my_zsh_dir }}/custom/plugins/zsh-syntax-highlighting"
    version: master
    depth: 1
  become_user: "{{ user }}"

- name: Configure Zshrc
  ansible.builtin.copy:
    dest: "{{ zsh_home }}/.zshrc"
    content: |
      export ZSH="{{ zsh_oh_my_zsh_dir }}"
      ZSH_THEME="gentoo"
      zstyle ':omz:update' mode auto
      zstyle ':omz:update' frequency 7
      plugins=(git zsh-completions zsh-autosuggestions zsh-syntax-highlighting)
      source $ZSH/oh-my-zsh.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  when: not zshrc.stat.exists

- name: Set Zsh as Default Shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
