apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: antimeta
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nayetdet/homelab.git
    targetRevision: main
    path: charts/workloads/antimeta
  destination:
    server: https://kubernetes.default.svc
    namespace: antimeta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
