antimeta:
  env:
    LINKEDIN_JOB_SEARCH_HOURS_OLD: "4"
    LINKEDIN_JOB_APPLICATION_MAX_STEPS: "3"
    LLM_MODEL: openai/gpt-5.4-nano

  secrets:
    application:
      externalSecret:
        enabled: true
    registry:
      externalSecret:
        enabled: true
        storeName: vault-oci
        remoteKey: nayetdet

  filebrowser:
    enabled: true
    auth:
      enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        integrations:
          certManager:
            enabled: true
            certificateIssuer: home-ca
          traefik:
            enabled: true
            entrypoints:
              - websecure
            forceTLS: true
        hosts:
          - host: antimeta.home.arpa
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: antimeta-tls
            hosts:
              - antimeta.home.arpa
