antimeta:
  env:
    LINKEDIN_JOB_SEARCH_HOURS_OLD: "4"
    LINKEDIN_JOB_APPLICATION_MAX_STEPS: "3"
    LLM_MODEL: openai/gpt-5.4-nano

  secrets:
    application:
      externalSecret:
        enabled: true
    registry:
      name: garapatech-oci
      externalSecret:
        enabled: true
        storeName: vault-oci
        remoteKey: nayetdet

  files:
    enabled: true
    create: false
    secretName: files-secret

  filebrowser:
    enabled: true
    auth:
      enabled: false
    persistence:
      resume-files:
        enabled: true
        type: secret
        objectName: files-secret
        optional: true
        mountPath: /data/resumes
        items:
          - key: resume_en_US.json
            path: resume_en_US.json
          - key: resume_pt_BR.json
            path: resume_pt_BR.json
        targetSelector:
          main:
            main: {}
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        integrations:
          certManager:
            enabled: true
            certificateIssuer: home-ca
          traefik:
            enabled: true
            entrypoints:
              - websecure
            forceTLS: true
        hosts:
          - host: antimeta.home.arpa
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: antimeta-tls
            hosts:
              - antimeta.home.arpa
