apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/nayetdet/charts
    chart: gatekeeper
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
