---
- name: Install Helm APT dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - gpg
      - python3-debian
    state: present
    update_cache: true

- name: Download Helm APT repository key
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /tmp/helm-apt-key.asc
    mode: "0644"

- name: Install Helm APT repository key
  ansible.builtin.command:
    cmd: gpg --dearmor --yes --output /usr/share/keyrings/helm.gpg /tmp/helm-apt-key.asc
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: Configure Helm APT repository
  ansible.builtin.deb822_repository:
    name: helm-stable-debian
    types: deb
    uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
    suites: any
    components:
      - main
    signed_by: /usr/share/keyrings/helm.gpg
    state: present

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
