---
- name: Install Curl
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: Ensure K3s Configuration Directory Exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure Host Resolver for K3s
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  notify: restart-k3s

- name: Configure K3s Resolver
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/config.yaml
    content: |
      resolv-conf: /run/systemd/resolve/resolv.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart-k3s

- name: Install K3s Server and Worker
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 0644
  args:
    creates: /usr/local/bin/k3s
  register: k3s_install
  retries: 3
  delay: 10
  until: k3s_install.rc == 0
  notify: restart-k3s

- name: Ensure K3s Service Is Enabled and Running
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Create Kubectl Configuration Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
  when: ansible_user != 'root'

- name: Configure Kubectl for the Ansible User
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: ansible_user != 'root'
